"use client";

import { v3 as uuidv3 } from "uuid";
import TitleSection from "../../../components/TitleSection";
import GeneratorDisplay from "../../../components/GeneratorDisplay";
import InfoSection from "../../../components/InfoSection";

export default function UUIDV3Page() {
  const generateV3 = () => {
    const namespace = uuidv3.DNS;
    const name = `example-${Date.now()}-${Math.random()}`;
    return uuidv3(name, namespace);
  };

  return (
    <>
      <TitleSection
        title="UUID v3 Generator"
        subtitle="Name-based UUID using MD5 hashing"
      />
      <GeneratorDisplay label="Generated UUID v3" generateFn={generateV3} />
      <InfoSection
        title="About UUID v3"
        info="UUID Version 3 is generated by hashing a namespace identifier and a name using MD5. The same namespace and name will always produce the same UUID. This version is deterministic and useful when you need to generate the same UUID from the same input. However, MD5 is considered cryptographically weak, so v5 (SHA-1) is preferred for new applications."
      />
    </>
  );
}
