"use client";

import { v3 as uuidv3, v5 as uuidv5 } from "uuid";
import TitleSection from "../../../components/TitleSection";
import GeneratorDisplayWithInput from "../../../components/GeneratorDisplayWithInput";
import DetailedInfoSection from "../../../components/DetailedInfoSection";

export default function UUIDV3Client() {
  return (
    <>
      <TitleSection
        title="UUID v3 Generator"
        subtitle="Name-based UUID using MD5 hashing"
      />
      <GeneratorDisplayWithInput
        label="Generated UUID v3"
        generateFn={(inputs) => {
          const namespace = uuidv3.DNS;
          const name = inputs.name || "example";
          return uuidv3(name, namespace);
        }}
        inputFields={[
          {
            name: "name",
            label: "Name",
            type: "text",
            placeholder: "Enter a name to generate UUID from",
            defaultValue: `example-${Date.now()}`,
            required: true,
          },
        ]}
      />
      <DetailedInfoSection
        about="UUID Version 3 is generated by hashing a namespace identifier and a name using MD5. The same namespace and name will always produce the same UUID, making it deterministic. This version is useful when you need to generate consistent UUIDs from the same input across different systems. However, MD5 is considered cryptographically weak and vulnerable to collision attacks, so v5 (SHA-1) is strongly preferred for new applications."
        useCases={[
          "Generating consistent IDs from URLs or domain names",
          "Creating deterministic UUIDs from user input",
          "Mapping names to UUIDs in a predictable way",
          "Legacy systems using MD5-based UUIDs"
        ]}
        howToGenerate={{
          library: "uuid",
          npmPackage: "npm install uuid",
          codeExample: `import { v3 as uuidv3 } from 'uuid';\nconst namespace = uuidv3.DNS; // or uuidv3.URL, uuidv3.OID, uuidv3.X500\nconst name = 'example.com';\nconst id = uuidv3(name, namespace);\nconsole.log(id); // Always the same for same name/namespace`,
          note: "Warning: MD5 is cryptographically weak. Use UUID v5 (SHA-1) for new applications requiring name-based UUIDs."
        }}
      />
    </>
  );
}

