"use client";

import { v3 as uuidv3, v5 as uuidv5 } from "uuid";
import TitleSection from "../../../components/TitleSection";
import GeneratorDisplayWithInput from "../../../components/GeneratorDisplayWithInput";
import InfoSection from "../../../components/InfoSection";

export default function UUIDV3Client() {
  return (
    <>
      <TitleSection
        title="UUID v3 Generator"
        subtitle="Name-based UUID using MD5 hashing"
      />
      <GeneratorDisplayWithInput
        label="Generated UUID v3"
        generateFn={(inputs) => {
          const namespace = uuidv3.DNS;
          const name = inputs.name || "example";
          return uuidv3(name, namespace);
        }}
        inputFields={[
          {
            name: "name",
            label: "Name",
            type: "text",
            placeholder: "Enter a name to generate UUID from",
            defaultValue: `example-${Date.now()}`,
            required: true,
          },
        ]}
      />
      <InfoSection
        title="About UUID v3"
        info="UUID Version 3 is generated by hashing a namespace identifier and a name using MD5. The same namespace and name will always produce the same UUID. This version is deterministic and useful when you need to generate the same UUID from the same input. However, MD5 is considered cryptographically weak, so v5 (SHA-1) is preferred for new applications."
      />
    </>
  );
}

