"use client";

import { v5 as uuidv5 } from "uuid";
import TitleSection from "../../../components/TitleSection";
import GeneratorDisplay from "../../../components/GeneratorDisplay";
import InfoSection from "../../../components/InfoSection";

export default function UUIDV5Page() {
  const generateV5 = () => {
    const namespace = uuidv5.DNS;
    const name = `example-${Date.now()}-${Math.random()}`;
    return uuidv5(name, namespace);
  };

  return (
    <>
      <TitleSection
        title="UUID v5 Generator"
        subtitle="Name-based UUID using SHA-1 hashing"
      />
      <GeneratorDisplay label="Generated UUID v5" generateFn={generateV5} />
      <InfoSection
        title="About UUID v5"
        info="UUID Version 5 is generated by hashing a namespace identifier and a name using SHA-1. Like v3, it's deterministic - the same namespace and name will always produce the same UUID. Version 5 is preferred over v3 because SHA-1 is more secure than MD5. It's useful when you need to generate consistent UUIDs from the same input."
      />
    </>
  );
}
