"use client";

import { v5 as uuidv5 } from "uuid";
import TitleSection from "../../../components/TitleSection";
import GeneratorDisplayWithInput from "../../../components/GeneratorDisplayWithInput";
import DetailedInfoSection from "../../../components/DetailedInfoSection";

export default function UUIDV5Client() {
  return (
    <>
      <TitleSection
        title="UUID v5 Generator"
        subtitle="Name-based UUID using SHA-1 hashing"
      />
      <GeneratorDisplayWithInput
        label="Generated UUID v5"
        generateFn={(inputs) => {
          const namespace = uuidv5.DNS;
          const name = inputs.name || "example";
          return uuidv5(name, namespace);
        }}
        inputFields={[
          {
            name: "name",
            label: "Name",
            type: "text",
            placeholder: "Enter a name to generate UUID from",
            defaultValue: `example-${Date.now()}`,
            required: true,
          },
        ]}
      />
      <DetailedInfoSection
        about="UUID Version 5 is generated by hashing a namespace identifier and a name using SHA-1. Like v3, it's deterministic - the same namespace and name will always produce the same UUID. Version 5 is preferred over v3 because SHA-1 is more secure than MD5, though SHA-1 itself is now considered deprecated for cryptographic purposes. It's useful when you need to generate consistent UUIDs from the same input across different systems without coordination."
        useCases={[
          "Generating consistent IDs from URLs or domain names",
          "Creating deterministic UUIDs from user input or identifiers",
          "Mapping names to UUIDs in a predictable way",
          "Content-addressable storage systems",
          "Generating UUIDs from email addresses or usernames"
        ]}
        howToGenerate={{
          library: "uuid",
          npmPackage: "npm install uuid",
          codeExample: `import { v5 as uuidv5 } from 'uuid';\nconst namespace = uuidv5.DNS; // or uuidv5.URL, uuidv5.OID, uuidv5.X500\nconst name = 'example.com';\nconst id = uuidv5(name, namespace);\nconsole.log(id); // Always the same for same name/namespace`,
        }}
      />
    </>
  );
}

